database:
  default: mysql
  drivers:
    mysql:
      driver: mysql
      host: localhost
      port: 3306
      database: test
      username: root
      password: zhangjian
      charset: utf8
      table_prefix: ''
      max_idle_conn_num: 10
      max_open_conn_num: 100
      log_level: 4